# Generated by Django 4.2.16 on 2024-11-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_treatment_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='treatment_history',
            field=models.ManyToManyField(blank=True, related_name='client_treatment_history', to='clients.servicetitle', verbose_name='Historial de servicios | tratamientos'),
        ),
    ]
