# Generated by Django 4.2.16 on 2024-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_treatment_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetitle',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Titulo del servicio'),
        ),
    ]
