# Generated by Django 4.2.16 on 2024-11-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_servicetitle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='service_appointments', to='clients.servicetitle', verbose_name='Servicios | Tratamientos'),
        ),
    ]
