# Generated by Django 4.2.16 on 2024-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_appointment_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='titles',
            field=models.ManyToManyField(related_name='service_titles', to='clients.servicetitle', verbose_name='Servicios | Tratamientos'),
        ),
    ]
