# Generated by Django 4.2.16 on 2024-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_service_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='beautician',
            field=models.CharField(choices=[('lulu', 'Lulú')], default='Lulú', max_length=100),
        ),
        migrations.AddField(
            model_name='agreement',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='solicited_service', to='clients.servicetitle', verbose_name='Servicio solicitado'),
        ),
    ]
